default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *default
  database: devise_db
  username: nes_user
  password: darkstyle66

test:
  <<: *default
  database: devise_db
  username: nes_user
  password: darkstyle66

