# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4632ca17640b20e8d9fb973817c549b0bf2abadade9bc66c71848028ddcddf29e26cb9d71218c3addd5a645c69496a3ddbccf22415497092590f9d2493ca1bf9

test:
  secret_key_base: b47ed13232909421316d851802ea9d5635705294f09926b96dd2fbb14e171f370589f3173a3ff5731fbb90d28724881e09cf1fe8890c6584cdbe968ea75854fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
